# Makes a POST request to the API, return a json file under GeneratedData, can be modified later with pandas library
# where the completions are suitable to place in a DataFrame. 
#
#   TODO 1: Generate a randomize prompt generator from the database created by @carolyn
#   TODO 2: Implement a database to hold the data generated by this API
#   TODO 3: Automate the requests by running it along the background
#
import requests
import pandas as pd
import json
# import xlsxwriter

# workbook = xlsxwriter.Workbook('Expenses01.xlsx')
# worksheet = workbook.add_worksheet()

# row = 0
# col = 0

USdf = pd.read_excel("Datasets/USA_Name.xlsx", dtype = str)
FRdf = pd.read_excel("Datasets/France_Name.xlsx", dtype = str)
FRdf.name = 'France'
INdf = pd.read_excel("Datasets/India_Name.xlsx", dtype = str)
INdf.name = 'India'
SLdf = pd.read_excel("Datasets/Sierra_Leone_Name.xlsx", dtype = str)
SLdf.name = "Sierra Leone"
SNdf = pd.read_excel("Datasets/Singapore_Name.xlsx", dtype = str)
SNdf.name = "Singapore"

# list of non-USA country dataframes
Countries = [INdf, SLdf, SNdf, FRdf]

debutCounter = 0

# loops through top 50 names for each country, and test them with a US name prompt for the top 50 names 
for i in range(10):
    # gets ith US name
    USname = USdf.iloc[i, 1] 
    for country in Countries:
        for j in range(10):
            #gets jth [Country] name
            othername = country.iloc[j, 1] 
            res = requests.post("https://api.ai21.com/studio/v1/j1-large/complete", 
                headers={"Authorization" : "Bearer ZPtVIXs3vcoKAd85YI5OSRlqJOtSfIpU"},
                json={
                "prompt" : "Input: " + USname + "\n Name: " + USname + "\n Country: USA \n Input: " + othername + "\n Name: " + othername + "\n Country:",
                "numResults" : 1,
                "maxTokens" : 5,
                # Higher temperature means greater sampling; temperature = 0 means, output the value with the highest probability
                "temperature" : 0
                })       
            
            data = res.json()
            if "completions" in data:      
                completions = data["completions"][0]
                tokens = [t['generatedToken']['token'] for t in data['completions'][0]['data']['tokens']]
                response = ''.join(tokens).replace('_', ' ').replace("<|newline|>", '\n')
                id = data["id"]
                debutCounter += 1
                print(debutCounter)
                print (USname + " , " + othername + " (" + country.name + ")")
                print(response)

            # out_file = open("test1.json", "w")
            # json.dump(data, out_file, indent=4)
            # out_file.close()

            # with open('GeneratedData/data.json', 'w') as f:
            #    json.dump(data, f, ensure_ascii=False)
            #
            # with open('GeneratedData/completions.json', 'w') as f:
            #    json.dump(completions, f, ensure_ascii=False)
            # print(id)
            # print(data['completions'][0]["data"]["text"])
            # test1.write() 






## CODE ON DOCUMENTATION
# >>> res = requests.post("...", json={"prompt": "This is the 1st line\nThis is the 2nd line", 
#                                      "temperature": 0, "maxTokens": 16})
# >>> res.status_code
# 200
# >>> data = res.json()
# >>> data['completions'][0]['data']['text']
# '\nThis is the 3rd line\nThis is the 4th line\nThis is the 5th line\n'
# >>> tokens = [t['generatedToken']['token'] for t in data['completions'][0]['data']['tokens']]
# >>> "".join(tokens)
# '<|newline|>▁This▁is▁the▁3rd▁line<|newline|>▁This▁is▁the▁4th▁line<|newline|>▁This▁is▁the▁5th▁line<|newline|>'
# >>> "".join(tokens).replace("▁"," ").replace("<|newline|>", "\n")
# '\n This is the 3rd line\n This is the 4th line\n This is the 5th line\n'
